# ========================================================================
#              CONFIGURACION DE LA BASE DE DATOS POSTGRESQL
# ========================================================================

# URL de conexion para PostgreSQL
# (Usa host.docker.internal para conectar desde el contenedor a tu PC)
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/tienda_db

# Credenciales del superusuario de PostgreSQL
# RECUERDA CAMBIAR LA CONTRASENA POR LA TUYA
#spring.datasource.username=postgres
#spring.datasource.password=bdpostgress123

# --- Configuracion de JPA y Hibernate ---
# Le decimos a Hibernate que dialecto SQL debe usar para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Le pasamos el control total del esquema a Liquibase.
spring.jpa.hibernate.ddl-auto=validate

# --- Configuracion de Liquibase ---
# Le indicamos a Spring Boot la ruta de nuestro archivo maestro.
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Ruta de la documentacion de swagger
springdoc.api-docs.path=/api-docs

# Le dice a Spring Boot que confie en las cabeceras del proxy para determinar la URL correcta
server.forward-headers-strategy=framework